# Generated by Django 3.0.2 on 2020-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
